export const CARD_ROW_IMG_RATIO = 583 / 266;
export const CARD_IMG_RATIO = 288 / 158;

export const BOX_SHADOW_COMMON = "0 25px 50px -12px rgb(0 0 0 / 0.25)";

export const cardList = [
  {
    id: 1,
    img: "/images/cardItem.png",
    category: "Education",
    title: "Powered Kits Learning Boxes",
    description: "Fun, durable and reusable boxes with eco friendly options.",
    amount: 2000,
    backers: 173,
    raised: 1900,
    avatar: "/images/cat.avif",
    author: "Mahfuzul Nabil",
  },
  {
    id: 2,
    img: "/images/cardItem2.png",
    category: "Real Estate",
    title: "Building Hope Village",
    description: "Together we can create access for everyone!",
    amount: 250,
    backers: 50,
    raised: 1900,
    avatar: "/images/cat.avif",
    author: "Adom Shafi",
  },
  {
    id: 3,
    img: "/images/cardItem3.png",
    category: "Real Estate",
    title: "New iMac For My Business!",
    description: "My computer decided to die. As a result, my small business.",
    amount: 1200,
    backers: 12,
    raised: 1800,
    avatar: "/images/cat.avif",
    author: "Sami Ahmed",
  },
  {
    id: 4,
    img: "/images/cardItem4.png",
    category: "Home",
    title: "The Watchman's Chairs",
    description:
      "Your home for indie and classic cinema has just been handed an...",
    amount: 5000,
    backers: 1000,
    raised: 10900,
    avatar: "/images/cat.avif",
    author: "Nill",
  },
];

export const listPayment = [
  {
    id: 1,
    name: "Paypal",
    logoSrc: "/images/logoPaypal.png",
    desc: "Get paid directly via Paypal.",
  },
  {
    id: 2,
    name: "Payonner",
    logoSrc: "/images/logoPayonner.png",
    desc: "Get paid worldwide your Work.",
  },
];

export const listWithdraw = [
  {
    id: 1,
    img: "/images/cardItem.png",
    title: "One Special 4K Camera",
    date: "6 March 2023",
    category: "Camera Gear",
    amount: 500,
    author: "Mahfuzul Nabil",
    rating: 4,
  },
  {
    id: 2,
    img: "/images/cardItem2.png",
    title: "Cool Comfy Shoes Easy You ",
    date: "6 March 2023",
    category: "Clothe & Wearable",
    amount: 2550,
    author: "Adom Shafi",
    rating: 3,
  },
  {
    id: 3,
    img: "/images/cardItem3.png",
    title: "The Watchman's Chairs",
    date: "6 March 2023",
    category: "Home",
    amount: 1550,
    author: "Adom Shafi",
    rating: 5,
  },
  {
    id: 4,
    img: "/images/cardItem4.png",
    title: "“Lost Soul” graphic novel",
    date: "6 March 2023",
    category: "Comics",
    amount: 1550,
    author: "Adom Shafi",
    rating: 4,
  },
  {
    id: 5,
    img: "/images/cardHeader1.avif",
    title: "Building Hope Village",
    date: "6 March 2023",
    category: "Real Estate",
    amount: 3550,
    author: "Sajib Rahman",
    rating: 4,
  },
  {
    id: 6,
    img: "/images/cardHeader2.avif",
    title: "Building Hope Village",
    date: "6 March 2023",
    category: "Real Estate",
    amount: 3550,
    author: "Sajib Rahman",
    rating: 4,
  },
  {
    id: 7,
    img: "/images/card1.avif",
    title: "New iMac For My Business!",
    date: "6 March 2023",
    category: "Accssories",
    amount: 50,
    author: "Delowar H.",
    rating: 1,
  },
];
